site_name: dekube
site_url: https://docs.dekube.io/
site_description: "Convert Kubernetes manifests to compose.yml. Sanity may or may not be included."
repo_url: https://github.com/dekubeio/dekube-engine
repo_name: dekubeio/dekube-engine


theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  custom_dir: overrides
  features:
    - navigation.sections
    - content.code.copy
    - search.suggest

nav:
  - Home: index.md
  - Understand:
      - Concepts: understand/concepts.md
      - Architecture: understand/architecture.md
      - dekube-engine: understand/engine.md
      - Distributions: understand/distributions.md
      - Build system: understand/build-system.md
  - Extend:
      - Code quality: extend/code-quality.md
      - Testing: extend/testing.md
      - Writing extensions:
          - Overview: extend/extensions/index.md
          - Converters: extend/extensions/writing-converters.md
          - Providers: extend/extensions/writing-providers.md
          - Transforms: extend/extensions/writing-transforms.md
          - Rewriters: extend/extensions/writing-rewriters.md
          - Ingress providers: extend/extensions/writing-ingressproviders.md
  - Extension catalogue: catalogue.md
  - Troubleshooting: troubleshooting.md
  - Limitations: limitations.md
  - Roadmap: roadmap.md
  - Journal: journal.md
  - About: about.md

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true

copyright: Public domain. No rights reserved. No tentacle returns. (Built with <a href="https://squidfunk.github.io/mkdocs-material/">MkDocs Material</a>)
